version: "3"
services:
  defever_database:
    image: postgres:16.0-bookworm
    container_name: defever_db_wc
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - /Users/umerraja/Repositories/defever_data:/var/lib/postgresql/data # For presistent database volumes locally
    #restart: always

  defever_application:
    image: defever_img  # for using an already created sping boot app image
    # build: . # To create an image of sping boot application with Dockerfile in same directry.
    #or
    # dockerfile:Dockerfile # To create an image of sping boot application with this docker file.
    container_name: defever_con_wc
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - defever_database
    #restart: always

