version: "3"
services:
  spring-app:
    image: defever-image
    container_name: defever
    ports:
      - "8080:8080"
    env_file:
      - .env

  database:
    image: postgres:latest
    container_name: defever_db
    env_file:
      - .env
    ports:
      - "5430:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: