version: "3"
services:
  database:
    image: postgres:11-alpine
    environment:
       - POSTGRES_DB=defever 
       - POSTGRES_USER=usaghir
       - POSTGRES_PASSWORD=Random001
    ports:
      - "5430:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
