server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://172.21.0.2:5432/postgres
    username: postgres
    password: example
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:postgresql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME}
#    username: ${DEV_DB_USERNAME}
#    password: ${DEV_DB_PASSWORD}
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
