#spring:
#  profiles:
#    active: prod
#
#server:
#  port: 8080
##
##spring:
##  datasource:
##    url: jdbc:postgresql://172.21.0.2:5432/postgres
##    username: postgres
##    password: example
##  jpa:
##    show-sql: true
##    generate-ddl: true
##    hibernate:
##      ddl-auto: update