spring:
  datasource:
    url: jdbc:postgresql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_USERNAME}
    name: ${DEV_DB_NAME}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
